version: '3.9'

services:

  # Shibboleth sp in one container targeting "app" in separate container over network bridge
  shibsp:
    image: ${DOCKER_REGISTRY}/bu-shibboleth-sp 
    container_name: sp    
    build:
      context: ./
      dockerfile: Dockerfile-sp
    environment:
      TZ: UTC
      AWS_PROFILE: ${AWS_PROFILE}
      EXPRESS_PORT: ${EXPRESS_PORT:-5000}
      ENTITY_ID: ${ENTITY_ID}
      IDP_CERT: ${IDP_CERT}
      ENTRY_POINT: ${ENTRY_POINT}
      LOGOUT_URL: ${LOGOUT_URL}
      SAML_CERT: ${SAML_CERT}
      SAML_PK: ${SAML_PK}
      DOCKER_PROFILE: integrated
      APP_HOST: app
      # DEBUG: 'true'
    ports:
      - '${EXPRESS_PORT:-5000}:${EXPRESS_PORT:-5000}'
    networks:
      wp-bridge:

  app:
    image: ${DOCKER_REGISTRY}/bu-shibboleth-app 
    container_name: app 
    build:
      context: ./
      dockerfile: Dockerfile-app
    depends_on:
      - shibsp
    expose:
      - 443
    environment:
      EXPRESS_PORT: 443
      # DEBUG: 'true'
    networks:
      wp-bridge:
    
 
networks:
  wp-bridge:
    driver: bridge

